### ISSUE TITLE
Settings menu contents

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#19]
- graphical settings should be separated from algorithm settings (we should not mix them in one dialog box but have two separate dialog boxes)
- what ideally should be available in **graphical settings** (if something is very difficult we can omit it):
  - currency and probability decimal point and currency thousand separator (now it is only `.` and `,` should be possible to change to `,` and whitespace) in this way we would handle US and Polish styles
  - text font
  - text font size
  - color selector for nodes
  - color and thickness selector for optimal/not-optimal/highlighted edge
  - color selector for payoffs on decision/chance nodes, on terminal nodes, on edges
  - color selector for probabilities
  - color selector for edge labels
  - color selector for node labels

We do not need a fancy color selector if it would mean dependencies on additional libraries - it may be even a list of colors or hex value of a color. The same for fonts: `serif`, `sans-serif` and `monospace` is enough.

**Comment by annawier** [comment]
- default colors for positive/negative payoffs
- settings for different colors of selected objects
- default values for font, number format locale and currency
all above is already in documentation

only recommended settings for chosen standard locales left, but it's a different issue
