### ISSUE TITLE
Default layout mode and layout settings saving

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#30]
@mwasiluk
- Make `tree` layout a default layout.
- Tree layout mode should be saved in tree metadata
- Tree layout parameters (margins etc.) should be saved in tree metadata

@pszufe
- this should be documented
- in particular, make a recommendation in the documentation that `tree` layout is recommended when developing the tree and `manual` layout is preferred is final corrections are made

**Comment by annawier** [comment]
documented:
- `tree` as a default layout (it's mentioned in a few sections e.g. layout settings or toolbar actions)
- `tree` recommended when developing the tree and `manual` when it's almost finished (documented in "tips &trics")
-  'layout options saved in tree metadata' documented in a few sections
