### ISSUE TITLE
Documentation of wrong input handling

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#36]
@pszufe @annawier 
SilverDecisions has the following error control:
1) dangling Chance/Decision node, signified with `!!`
2) probabilities do not add up to 1 in chance node, signified with `!!`
3) wrong format of number in input field (in particular empty field left); **no error shown** globally, red underline when editing; after exiting the node old value (before the error) is retained; THIS IS NOT OBVIOUS
4) settings dialog: errors are not marked; if there is an error it is **silently** replaced by default value or last value; THIS IS NOT OBVIOUS (and the general conclusion is that user should use settings with care and know what she is doing)

@mwasiluk If you plan to change the input error control relative to what I described above please let us know.

**Comment by annawier** [comment]
all of them documented in settings' field
