### ISSUE TITLE
Add more algorithms for selection of best subtree

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#37]
Apart from expected value maximization we want at least the following decision making rules in the engine:
1. Maxi-min (in chance node we always take the value of the worst option: pessimistic approach)
2. Maxi-max (in chance node we always take the value of the best option: optimistic approach)

We do not need it before go-public but it is an important future requirement.

**Comment by bkamins** [comment]
@mwasiluk I like the way 77f837f70976a61 was implemented.

@michaljakubczyk Please checkout dev branch (if you do not know how to do it give me a call) and tell me if it is also a good way to show maxi-min and maxi-max solutions. In general the key functionality that should be discussed is:
* green path is the path only on selected route from chance node (as compared to EV maximization, where all routes from chance node are highlighted);
* the probabilities shown in terminal nodes are updated and actually chosen nodes have probability 1.0 and all other nodes have probability 0.0;

I accept both as in maxi-min and maxi-max rules we disregard probabilities in chance nodes anyway.

**Comment by bkamins** [comment]
@michaljakubczyk any comments?

**Comment by bkamins** [comment]
Functionality accepted

**Comment by bkamins** [comment]
@annawier please document the functionality

**Comment by annawier** [comment]
done in Toolbar actions
