### ISSUE TITLE
Tree parameters metadata

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#38]
This is a major but not urgent requirement (we should do it only after everything else is finished).

It should be possible to have tree parameters metadata dialog where we define variables and set their values, eg. "p=0.5".

Then it should be possible to use the variables from tree parameters metadata to calculate probabilities and payoffs in the tree (eg. to have formulas like probability "p" in one edge from a chance node and "1-p" in the other edge).

The functionality is desirable because in typical trees in different part of the tree we have the same "subproblem" solved. Now we handle it by copy-paste, but then changing one subtree requires manual changing of copied subtrees.

**Comment by bkamins** [comment]
More details about the expected functionality.

I recommend to keep definitions of variables in **right pane** (that would be like current left pane, but on the right side).
It should be possible to add new variables following these rules:
- variable is case sensitive and accepts only letters `[a-zA-Z]+`;
- value of the variable can only be a proper number (using variables, formulas or `#` in variable value definition is not allowed); *this might change in the future but for now I want to enforce it for simplicity*
- it should be not possible to add two variables with the same name

How variables are used:
- variables can be used in specifying payoffs and probabilities
- if a formula is malformed (e.g. variable does not exist) or yields improper result (eg. negative probability) then `!!` should be reported in a proper placed
- a result of calculation should be shown somewhere (need to see to decide where :))

What we accept in formulas (*this might change in the future but for now I want it simple*):
- properly formatted numbers
- existing variables
- `-`, `+`, `*`, `/`, `^` (exponentiation)
- `(`, `)`
- `exp`, `log`

**Warning!** When tree is flipped #42 all formulas are replaced by their values. The result of tree flipping is only actual values. (*this might change in the future but for now I want it simple*)

**Comment by mwasiluk** [comment]
As to expressions syntax we already use math.js expression engine to compute payoffs and propabilities:
http://mathjs.org/docs/expressions/index.html

Main thing missing is setting variables in the scope.

**Comment by bkamins** [comment]
@mwasiluk this is really nice as I understand that you pass `scope` parameter to `eval` which should contain the variables you want and this should be simple to implement. Do I understand this correctly?

The other thing to remember is that after #64 we have to handle single `#` case separately.

**Comment by bkamins** [comment]
We just have to mind possible side effects introduced by the library in general.
E.g. user might call `random` which will yield varying result on every call (and we must make sure that tree solver handles this properly). However, in general this might be useful in the future (when we implement Monte Carlo simulation and allow users to define non-deterministic payoffs).

**Comment by bkamins** [comment]
@michaljakubczyk related to #66 and #68:
As a second thought is it acceptable in the future that:
*When tree is flipped #42 all formulas are replaced by their values. The result of tree flipping is only actual values. (this might change in the future but for now I want it simple)*

Maybe in long run we would have to perform algebraic transformation of formulas during flipping? Please comment if this is needed.

**Comment by bkamins** [comment]
@mwasiluk after a discussion if it would be possible to perform algebraic transformation of formulas when #42 this would be nice. This can be even simple pasting of strings (no need to parse the evaluation tree in maths library we use). We are open for discussion.

@michaljakubczyk but this is messy:
We probably actually need two modes when doing #42 transformation: *no formulas* (only numbers and `#`) and *at least one formula*;

In the latter case
- Such a transformation should assume that the probabilities given by formulas are strictly inside ]0,1[ interval, are proper etc.., so we do not handle "division by 0" properly in general;
- `#` should be replaced by the formula `1-([sum of all non # formulas in a node])/[number of #]` if any formula appears in the probabilities

**Comment by pszufe** [comment]
@mwasiluk now after some discussion with @bkamins we have decided that the parameter list should be rather in the existing left Pane - let's not create a new right pane for that

**Comment by bkamins** [comment]
After understanding #64 I would opt for something like this:

1) payoffs can be any proper single line expression of maths.js, example
```
exp(a)^2
```
2) probabilities can be `#` or any proper single line expression maths.js, example
```
x = random()
```
3) variables and preprocessing code is defined in a pop-up window as a free text of proper maths.js (multiline)

If payoff or probability evaluates to something else than a number this is an error (or throws exception).

How it should work:
1) workspace is cleaned
2) first preprocessing code is evaluated (line by line from first to last)
3) next BFS evaluation of first payoffs next probabilities in trees is performed (when order is visual top-down); each evaluation is performed only once (to allow randomness, e.g. `pickRandom([1, 2, 3])`); except `#` entries in probability edges, which are processed after everything else is processed; if there are multiple trees they are processed top-down also; the BFS order is important because expressions can have side effects (most notably introduce variables)
4) next normal solving of a tree is performed

Randomness can be later used as one of the ways sensitivity analysis in #68 is performed, but for now we ignore the distribution and simply perform only one computation of tree output.

This also means that:
1) tree should be automatically recomputed if it is changed in any way (including visual change, as it might affect BFS evaluation of nodes)
2) there should be a button "Recompute" and a sensible shortcut key for it (non-conflicting; e.g. now unfortunately under Linux Ctrl-Alt-T launches terminal) to recompute the tree
3) the same tree may be valid or invalid due to randomness in different runs (and we have to remember this)

@mwasiluk how do you see it? For me:
1) this allows for a lot of flexibility for the future
2) actually we do not have to restrict anything and coding it should be less error prone than careful checking what is allowed
3) this gives a risk that user might not use this properly, but we can teach them (a book is underway)
4) in the future of #68 we will probably inject some step between preprocessing and BFS evaluation to allow automated sensitivity analysis (I did not think how it should be visualized, but in the end from computational point of view it should be another code that is run after preprocessing and before BFS evaluation)
5) composition of expressions for tree flip should not be a problem, however we have to remember to replace `#` not by value but by expression of the kind `(1-([some sum])) / [number of #])`; the only problem is when in `some sum` there is explicit randomness (if randomness is via variable this is not a problem); I would disregard it and simply clearly document this that users should not put randomness in computations directly but via variables if they want to perform transformations of the tree (currently tree flip, but possibly something else in the future)

**Comment by bkamins** [comment]
@mwasiluk @michaljakubczyk 
One more thing we did not discuss: how do we handle tree flipping?
Do we construct expressions (i.e. after the flip the tree is still parameterized) or simply input values (tree flip looses the link with underlying variables).

**Comment by bkamins** [comment]
and one thing to document: these functions do not guarantee full precision (i.e. we operate on folats not on rationals).

@mwasiluk I understand that it is possible to mix rationals and floats in one tree.

**Comment by bkamins** [comment]
@mwasiluk
1. please also put `recalculate` button on top-level button bar (not only in global variables dialog) - it can be the same button visually. This is needed because in general change of code might happen in many places so we need a global recalculate button.
2. It would be good to make sure that in the tree expressions are evaluated only once and then all calculations (validation, optimization, etc.) on the value of this single evaluation. Simple example: `2*random()` in edge specifying probability (it is either invalid or valid - and we have to avoid the case that it passes through validation as less than 1 but then goes into optimization of the tree as another random value greater than `1`).

**Comment by bkamins** [comment]
And the core agreed functionality:

Functionality for current release:
* logo: material/text format
* variables are defined only in global scope
* it is not allowed to define variables in the tree (and this is checked by application)
* if text in tree is not valid it is retained but `!` is shown next to the error
* in documentation we have to describe what is possible and warn users about proper usage of functions with side effects
* in the future we might add definitions of variables in nodes via closures (currently tracked in #63)
* global box for definition of variables will have a `recalculate` button allowing for manual recalculation of defined variables (needed for `random`)

**Comment by bkamins** [comment]
And the core agreed functionality:

Functionality for current release:
* logo: material/text format
* variables are defined only in global scope
* it is not allowed to define variables in the tree (and this is checked by application)
* if text in tree is not valid it is retained but `!` is shown next to the error
* in documentation we have to describe what is possible and warn users about proper usage of functions with side effects
* in the future we might add definitions of variables in nodes via closures (currently tracked in #63)
* global box for definition of variables will have a `recalculate` button allowing for manual recalculation of defined variables (needed for `random`)

**Comment by bkamins** [comment]
@mwasiluk and one more thing (probably obvious): calculation of values for `#` should be made after all other evaluations have been mades.

**Comment by bkamins** [comment]
tree flipping: the decision is that if a subtree is flipped it is first evaluated and after the tree flip only values are retained in resulting tree (no formulas). This should ensure a consistent work with closures that are planned to be introduced in the future.
@michaljakubczyk when you document *tree flipping* you can already say that this functionality (as already we allow simple expressions - and they will be evaluated).

**Comment by bkamins** [comment]
@mwasiluk 

- Just to make sure - we should allow comments in the code specifying variables. I understand that `#` is a comment in mathjs.
- I would disallow comments in probabilities and payoffs specification fields (like we disallow assignment). This means in particular that `#` has still to be specially treated in chance nodes as it is now.
- we have to remember that if user defines functions in code specifying variables then those functions might have side effects and change values of existing variables but we would not be able to control that (needs to go into docs). I am thinking of something like

```
z = [0]
t() = z[1] = z[1] + 1
```
in global scope, and then we call function `t()` in payoff nodes and it changes `z` and the order of changes is unspecified. Such code should be discouraged in manual.

@mwasiluk regarding last point: is my understanding correct?

**Comment by bkamins** [comment]
Actually because of the last point maybe we can allow anything in probability and chance nodes definitions that parses correctly (the code to handle it will be simpler) but simply discourage making assignments there in the documentation.

This means that also comments would be allowed, but still we have to treat single `#` in a special way in probability specification. However, adding spaces around it like `#⍽` or `⍽#` should be an error as it produces `nothing`. Only bare `#` should be accepted.

**Comment by bkamins** [comment]
@mwasiluk bits and pieces:
1) now `⍽#⍽` and other like this are parsed as `#` in probabilities in chance edges (probably due to trimming?) - we can leave it "as is" but let's just confirm that this was intended
2) definition of variables in `payoff` and `probability` fields is not allowed. This is also OK, and after thinking should be like this but let us confirm that it was intended

additionally I give a "hard case". Please comment what you think is going on here (and definitely we should discourage such code):
<img width="729" alt="error" src="https://cloud.githubusercontent.com/assets/6187170/22226749/ed925020-e1c7-11e6-8cc4-e95a0569021d.png">
I show side by side global scope and definition of upper edge.

What happens:
* SAVE button stops to work (that is why I give you image and not a JSON file)
* variable `a` is not updated in scope of `chance node` you can see that evaluated variables is `a=[0.5, 0.7]` in chance node, but in global scope it is some random value in `a[1]` and they should be the same as `a` is not defined in inner scope (this is probably the reason of lexical scoping and `f` is in global scope but I do not know how you perform cloning)

Although we should discourage such code the above two behaviors worry me as they might happen in some normal situations so please investigate it (especially when user would define mutable objects - like arrays and they would be changed in inner scopes how would this behave?). If the case is not clear please let me know.

**Comment by bkamins** [comment]
@mwasiluk Also - are you sure that evaluation of expressions is done only once. In the above example it seems to me that `f()` gets called more than two times (and it should be called exactly two times when tree is recalculated)

**Comment by bkamins** [comment]
A minimal example when tree fails to save is the following code in global scope and empty canvas:
```
a=[1,2]
f()=3
```

**Comment by mwasiluk** [comment]
Expressions in nodes are evaluated in this way:
1. Scope is initialized as a deep copy of the parent scope
2. Code evaluation
3. Evaluation of 'numeric expressions' for each child edge (payoff, probability)

Steps 1 and 2 are performed only on 'full' recomputation.

Nodes are evaluated in depth-first order.

**Comment by bkamins** [comment]
@mwasiluk As far as I understand we are done with this one :). All the points raised here are fixed. We are left with some side issues to close.
