### ISSUE TITLE
Decision/chance node injection

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#39]
When we have an edge from node A to node B.
If we right click on this edge then we have two options "Inject Decision Node" and "Inject Chance Node".

If one of the options is chosen then a Decision/Chance node is added after the edge that was clicked but before node B. So that we have now a structure A-(new node)-B, and the properties of old A-B edge are now the same as properties of A-(new node) edge.

**Comment by mwasiluk** [comment]
I've also added keyboard interaction with the selected edge:
* Ctrl-Alt-D/C - inject decision/chance node

**Comment by bkamins** [comment]
@annawier when you document it please make sure to write that **edge** has to be selected in order to perform injection.

@mwasiluk a minor drawing bug: after node is injected the color arrowhead of selected edge is not correct (in default colors: it is not blue but black/green depending on if the edge is on optimal path).

**Comment by bkamins** [comment]
fixed

**Comment by annawier** [comment]
documented in tips&tricks
