### ISSUE TITLE
Compatibility with IE/EDGE

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#43]
<img width="959" alt="weird" src="https://cloud.githubusercontent.com/assets/6187170/20432916/b8931c60-ada1-11e6-9903-664556d9b09d.png">
This is minor (and I know we do not guarantee to support it, but maybe it is something simple).

In IE if you copy a subtree and then paste it the autolayout is not triggered.
However, after manual changing of the layout mode the result is OK.

Additionally when later you press undo-redo many times everything breaks up (see attached picture). In this state nothing works anymore.

Additionally saving JSON/PNG/SVG does not work on IE (at least on my computer).

On Edge JSON works, but PNG/SVG saving does not work.

@mwasiluk please have a look what could be done, as our MSFT-based user base is not neglible.

|Browser | Usage %|
|------------|------|
|Chrome | 48.23%|
|Firefox | 22.30%|
|Internet Explorer | 12.69%|
|Safari | 9.16%|
|Edge | 5.03%|

**Comment by bkamins** [comment]
@mwasiluk All else already mentioned works except saving PNG under IE - please check it.

Additionally under IE dialogs (Settings and About) do not get a scrolling bar (simply text overflows from the dialog box below the box and becomes illegible). This should be fixed

**Comment by bkamins** [comment]
502f14c works ok.
We are left with PNG save on IE.

**Comment by mwasiluk** [comment]
Making PNG work on IE would require additional library (eg [canvg](https://github.com/canvg/canvg)), as described [here](http://willkoehler.net/2014/11/07/client-side-solution-for-downloading-highcharts-charts-as-images.html#not-quite-so-fast).

I've tested canvg, but PNG is not rendered correctly.

**Comment by bkamins** [comment]
can we then show a popup "Export to PNG not supported in Internet Explorer." when PNG button is pressed in IE?

@annawier after tips&tricks section of documentation please add new "Known issues" section where we will document known problems with list of known limitations of SilverDecisions. This PNG incompatibility is first of them :).

**Comment by mwasiluk** [comment]
Maybe a popup "Export to PNG is not supported in your browser." would be better ? 
It would be shown whenever an exception occurs during an export.

**Comment by bkamins** [comment]
Great. Maybe use such catch-all phrase for other places with major functionality where exception can occur?

**Comment by bkamins** [comment]
OK. For now we are done with incompatibilities. Now it just needs to be documented.

**Comment by annawier** [comment]
incompatibility documentend in 'known issues' section
