### ISSUE TITLE
Wrong loading/saving of decision trees

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#45]
@mwasiluk Check out the "Investment in stock decision model" tree in [Gallery](https://github.com/bkamins/SilverDecisions/wiki/Gallery).

When you load the saved file the _description_ of the tree is not loaded although it is present in the JSON file (only title is loaded). Also _Layout_ options (layout, slant etc.) are not saved (or not loaded). Also please check if we save and load all settings properly.

**Comment by mwasiluk** [comment]
I can't reproduce this issue, the json file seems to load properly. I've tested it in Chrome, FF and Edge.
Maybe try refreshing app with Ctrl + F5 in chrome (it will clear the browser cache)

**Comment by bkamins** [comment]
@mwasiluk reopening the browser made the tree load properly. Please let me know what general text we should add to documentation, e.g. sth like:

```
Browsers often cache the ...
Therefore if SilverDecisions exhibits unexpected behavior, before submitting an issue with a bug, please make sure to refresh ... 
```

**Comment by pszufe** [comment]
Maybe we could set the .htacess file with such content to force the browser to completely reload every time the site is visited?

     Header unset ETag
     Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
     Header set Pragma "no-cache"
     Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"

**Comment by mwasiluk** [comment]
We could also append version number to the filenames in the docs, eg: silver-decisions-0.2.1.min.js

**Comment by pszufe** [comment]
Yes - but HTML can still reference the wrong version...

**Comment by mwasiluk** [comment]
It would require updating the filenames of the included files in html after every new release, but it could be done automatically with gulp.

**Comment by bkamins** [comment]
OK. @pszufe @mwasiluk Do whatever you find suitable. It should solve some class of problems (but probably not the one I was writing originally about as it was not due to caching old version of SilverDecisions)

**Comment by bkamins** [comment]
@mwasiluk closing as I understand we have it implemented.
