### ISSUE TITLE
Saving after loading of malformed JSON

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#49]
I have received JSON save file from older version of SilverDecisions. On load it generated error, but the tree appeared. I have modified the tree and saved it. The newly saved tree was still malformed (raised error on load). We could add checks for such situations.

**Comment by bkamins** [comment]
And in general from now on we should ensure that SilverDecisions is able to read files saved using its past versions. It should be easy because we save version info in JSON now.

If developer has to manually update version-info like in 8ec4108ed8cb8aa9 it should be put in developer's guide.

Additionally I would recommend that if we make breaking changes in save file format the major version number must be incremented by 1. I understand that adding new fields to JSON is **not breaking** as SilverDecisions ignores unused fields - is this correct?

The good thing is that we serve SilverDecisions so we do not have a problem of ensuring that new files have to be read by old versions of application (although adding a warning if file version info is larger than the version of application would be nice).

**Comment by bkamins** [comment]
Also related to 8ec4108 is that if we change SilverDecisions version number and js and css file names are changed then developer has to update SilverDecisions.html manually. This should also be put in release instructions in developers guide.

**Comment by mwasiluk** [comment]
@bkamins SilverDecisions.html is updated automatically with gulp docs-gen task

**Comment by bkamins** [comment]
OK. I leave it open till we have fallbacks implemented.

**Comment by bkamins** [comment]
OK - I understand that the amount of checks is reasonable :).
