### ISSUE TITLE
Wrong license in the "about" screen - should be LGPL

### ISSUE THREAD

**Issue by pszufe** [bkamins/SilverDecisions#51]
Michal, we need to update the licnse to LGPL. Otherwise we would have license crash with SPOD.

**Comment by pszufe** [comment]
Ania, now the manual got quite long. I believe just in the beginning we should very short "quick start" section (3 sentences) where user can find out that they should click with right mouse button to start drawing the tree and right click on parent node to add child nodes. I.e. if someidy wants just to try the software what they should click first...

**Comment by bkamins** [comment]
OK
