### ISSUE TITLE
Quick start manual section

### ISSUE THREAD

**Issue by pszufe** [bkamins/SilverDecisions#52]
Ania, now the manual got quite long. I believe just in the beginning we should very short "quick start" section (3 sentences) where user can find out that they should click with right mouse button to start drawing the tree and right click on parent node to add child nodes. I.e. if someidy wants just to try the software what they should click first...

**Comment by bkamins** [comment]
This is why I have created https://github.com/bkamins/SilverDecisions/wiki/Documentation#how-to-start-using-silverdecisions secion for.

**Comment by pszufe** [comment]
and that is where Ania will put this 3-sentence description :-)

**Comment by bkamins** [comment]
OK
