### ISSUE TITLE
Add an URL handler to silverdecisions to open JSON while starting the application

### ISSUE THREAD

**Issue by pszufe** [bkamins/SilverDecisions#53]
It should be possible to load SilverDecisions with a pre-opened JSON file. The file address should be given in the URL. This will enable to greatly increase functionality of tools such as our gallery. 
Moreover it will make it easier for citizens and public administration to share their trees with others. 

Sample URL could look like this:
http://www.silverdecisions.pl/SilverDecisions.html?LOAD_SD_TREE_JSON=https://raw.githubusercontent.com/wiki/bkamins/SilverDecisions/examples/decisiontree@2016.11.20_12.25.44.json

Application on load should check if the URL contains LOAD_SD_TREE_JSON parameter. When the answer is positive the tree should be loaded from the given location.

**Comment by bkamins** [comment]
@mwasiluk  maybe then we should also add a parameter if the tree should be editable or read only (see #18). However, I have never seen SilverDecisions in read-only mode, so maybe this is not a good idea.

**Comment by bkamins** [comment]
And then dynamically http://www.silverdecisions.pl/SilverDecisions.html could check if it is opened on tablet/mobile and start read-only mode (this would solve #18). In such case some non-intrusive information on the page informing if:
1) is application is in edit or read-only mode;
2) mobile/tablet was detected
would be nice.

@pszufe Is all this enchancement or rather future enchancement in your priorities?

**Comment by pszufe** [comment]
I have marked is enhancement. We want to do it right away because of (a) model gallery and more important (b) SPOD integration. 
Regarding "read only mode" and "tablet detection" - depends how much time it will take... I suppose tablet support could turn out to be huge and sophisticated software project due to browser incompatibilities (especially incompatibility on the library level...)

**Comment by mwasiluk** [comment]
I have added url handlers in docs/silverdecisions.js

**Comment by bkamins** [comment]
I am OK with this and we can leave tablet/mobile to #18. @pszufe if current functionality is what you wanted we can close this issue

**Comment by bkamins** [comment]
@pszufe I am closing this as the functionality is OK for me.
