### ISSUE TITLE
Number format locale in left panel not working

### ISSUE THREAD

**Issue by annawier** [bkamins/SilverDecisions#54]
@mwasiluk for probabilities and payoffs in left panel a dot "." seems to be the only one acceptable decimal mark, regardless number format locale settings (even if a comma is displayed on a diagram). Could you please check it?

**Comment by bkamins** [comment]
@annawier this is acceptable. I would rather simply document it that input is always expecting dot as decimal separator.

@mwasiluk if you want you can change it - please let us know what you think (but I do not want to have additional complexities in gui where they are not crucial).

**Comment by bkamins** [comment]
@annawier observe that the whole GUI of SilverDecisions is in English so this is consistent (and currently we do not plan to habe localized versions of SilverDecisions).

**Comment by annawier** [comment]
ok, for now i've just documented that 'left panel' accepts only a dot as a decimal mark
