### ISSUE TITLE
Add support for different languages

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#56]
In the future it would be nice to have SilverDecisions GUI in other languages with possibility to dynamically (or via URL parameter) change the locale.

**Comment by bkamins** [comment]
@mwasiluk "u mnie działa" 👍 .

Comments (no strong prefrence):
- ręczny -> "manualny"
- cluster -> maybe "zgrupowany"
- About is in english: @annawier provide @mwasiluk with Polish translation

@mwasiluk Can we close this issue (i.e. translations themselves will evolve, but is the core functionality finished - it seems to work - and we do not need an issue for corrections of translations).

**Comment by bkamins** [comment]
@pszufe please:
- document `lang=pl` option on Wiki
- comment if you think we should have exposed links to SilverDecisions in other languages on project website?

**Comment by bkamins** [comment]
@mwasiluk @pszufe will update `pl.json` so we will be left with translation of contents of *About*.

**Comment by pszufe** [comment]
Polish translations have been corrected. @mwasiluk now requires a rebuild/repackaging.

**Comment by annawier** [comment]
_About_ translation has just been sent to mwasiluk

**Comment by bkamins** [comment]
In a6d07532 and 0fb0a47 I have added one additional translation, requires rebuild.

@mwasiluk I want to close it but please confirm that we have implemented a fallback mechanism to English for missing translations.

**Comment by mwasiluk** [comment]
yes, there is a fallback to English for missing i18n keys
