### ISSUE TITLE
Documentation of SilverDecisions url parameters

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#57]
@pszufe please add to documentation a proper section on url parameters of SilverDecisions (currently we have a decision tree file location; in future we might have more)

**Comment by mwasiluk** [comment]
There is also readonly parameter, eg:
http://www.silverdecisions.pl/SilverDecisions.html?LOAD_SD_TREE_JSON=https://raw.githubusercontent.com/wiki/bkamins/SilverDecisions/examples/decisiontree@2016.11.20_12.25.44.json&readonly=true

**Comment by pszufe** [comment]
done

**Comment by bkamins** [comment]
Small fix needed in read only. I will correct it.
