### ISSUE TITLE
Ctrl-C/Ctrl-V when editing text fields in left pane

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#58]
@mwasiluk now Ctrl-C/Ctrl-V when editing text fields in left pane copies/pastes a subtree relative to the edited node. An intuitive behavior would be to copy text that is highlighted/paste text from clipboard. However, this might break Ctrl-C/Ctrl-V functionality of copying/pasting subtrees (I do not know the details of handling the focus in SilverDecisions).

The best option would be that Ctrl-C/Ctrl-V:
1) works on nodes if the focus is in plotting canvas;
2) works on text if the focus is in the text field;
3) does nothing (for now - as we might have some new functionality) if the focus is on any other component;

(note that even if the focus is in text field - option 2) - the node in canvas should remain selected). In general please advise the safest and most intuitive option to handle this. If we decided to follow my recommendation then Ctrl-A should be handled in similar way (now Ctrl-A works OK in option 2 but in other options it selects everything and the intuitive thing is to select all the nodes if focus is in canvas).
In order to implement all this there should be some visual indication of where the focus of application is (if we are in text field this is obvious as there is a blinking marker; but if the focus is on canvas I it is not shown; I am even not sure if currently we can talk about the concept of focus in SilverDecisions except text fields).

@annawier please document the behavior that we will decide to have.

**Comment by mwasiluk** [comment]
All keyboard shortcuts have already been ignored when focus was on an input field. 
Some of the input text fields were changed to textarea recently and I've forgotten to include them in a  key event source filtering.

**Comment by bkamins** [comment]
so I understand that you will fix it to work as I have described?

**Comment by mwasiluk** [comment]
After #016db2d all our custom keyboard shortcuts work only when focus is outside of input or textarea element.

**Comment by bkamins** [comment]
Works OK - I have missed the commit.

**Comment by bkamins** [comment]
Closing - as current behavior is obvious now and does not need documentation.
