### ISSUE TITLE
Change functionality of doubleclick

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#59]
Please vote if you accept if we changed reaction of the tree to double-click from:

```select subtree```

to

```open context menu```

(then right click and double click in canvas would have exactly the same effect)

**Comment by bkamins** [comment]
We have settled for the following functionality:

double click: open context menu (exactly the same as right click in canvas)

we have select subtree in context menu so this should be enough (no need of ctrl-doubleclick for this as the functionality is not needed very often).

What has to be updated:
1) @mwasiluk application code
2) @mwasiluk description in "about" dialog
3) @annawier documentation (when the change is commited to master)

**Comment by bkamins** [comment]
@mwasiluk functionality is OK on desktop. You have not updated "about" dialog section with help.
Functionality on tablet/mobile is not ok, but I treat this issue as resolved (keep it open for documentation) and will keep open #18 to fix tablet issue.

**Comment by bkamins** [comment]
To sum up: here we are left with update of "About"

**Comment by bkamins** [comment]
thx. we are left with the wiki documentation.

**Comment by annawier** [comment]
documented
