### ISSUE TITLE
Wrong pasting of disconnected graphs

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#6]
In the current default tree do the following steps:
1. select ONLY two green triangles
2. perform Copy
3. paste them either to one of the red squares
Result: only one of the triangles gets pasted.

The same behavior is if we paste to "canvas". The problem is if we paste any objects (two or more) that are not connected in a tree. It seems that only the object that is topmost vertically in canvas is pasted.

**Comment by annawier** [comment]
In Chrome ctrl+c & ctrl+v is not working properly. 
1. Select any node and ctrl+c
2. Right-click on the canvas
3. Press ctrl+v - nothing happens,

To copy the nodes/subtrees to the canvas I need to left-click and choose "paste" option from the context menu.
I think that ctrl+v works only for copying some nodes directly to the tree graph.

**Comment by bkamins** [comment]
@annawier this is an acceptable behavior. My understanding is that Ctrl-v should work only when a node is selected. I accept that Ctrl-v does not work when no node is selected (it could work but pasting a new subtree is a rare operation so it is not crucial). This should be documented though.

@mwasiluk what do you think.

**Comment by annawier** [comment]
ok, i've documented it in "Selecting, copying and pasting the nodes"
