### ISSUE TITLE
Tab behavior

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#62]
@mwasiluk Is it possible to have the following behavior:

using <kbd>Tab</kbd> if focus is in left pane in Edge or Node properties loops only the fields in left pane in this section (i.e. if we are in last field in Node properties and press <kbd>Tab</kbd> it moves focus to the first field).

It is not crucial but nice to have - if it is very messy we can live without it.

**Comment by bkamins** [comment]
@mwasiluk please let me know if this is something that we could implement.

**Comment by mwasiluk** [comment]
I don't think  it's recommended practice to change default tab behavior, because it will mess with page accessibility.

**Comment by mwasiluk** [comment]
You can always use shift + tab to go to previous field

**Comment by bkamins** [comment]
I know, just @michaljakubczyk wanted it. Closing the issue as won't-fix
