### ISSUE TITLE
Ideas for future functionalities

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#63]
This is a catch-all issue for ideas beyond currently planned releases (mainly for @mwasiluk so that it is clear what might be added as it may affect current design decisions). It is accepted that they are speculative and might be discarded after a discussion. I will update this initial post as we progress with concrete solutions. Discussion is welcome.

- add integration with Shiny (so that tree parameters can be tweaked externally from Shiny dashboards and the output is sent back to Shiny for analysis/visualization)
- add plugin engine for different payoff calculation modes, possible applications:
    - add possibility to specify utility function that would transform payoffs before optimization
    - add possibility to handle dual-utility (transformations of probabilities)
    - add possibility to handle contemporary decision making theories (prospect theory, range dependent utility etc.)
    - add complex aggregation over the path in a tree (e.g. discounting)

**Comment by bkamins** [comment]
I am moving "mulitple payoffs", "EVPI/EVII" and "sensitivity analysis" to separate issues as we have concluded that we want them and start planning the functionality.

**Comment by bkamins** [comment]
Another non-functional idea is to make SilverDecisions available as an app using Electron.

**Comment by bkamins** [comment]
@pszufe reports that pilots would like to transform trees to natural language descriptions. We assume that it would work only in English.

The steps to go forward with this are the following:
1. @pszufe prepares detailed description of the required algorithms and functionality
2. then we open an issue for implementation by @mwasiluk

**Comment by bkamins** [comment]
As an extension of #68 we consider to allow defining variables in nodes and properly handling closures defined by tree structure.

**Comment by bkamins** [comment]
@mwasiluk Regarding closures in #68, I understand that if we use `math.eval` and keep `scope` with values of already evaluated variables for each node this should be doable. Root node will use global scope as starting point, and each other node will have parent node's scope as starting point (I understand that actually the scope would have to be deep copied before evaluation to ensure that it would not be modified).
If we go this way then we would have to add `Code` field below `Label` field in each node and it would allow to define scope for evaluation in all children edges and nodes.

**Comment by bkamins** [comment]
@mwasiluk when we will do the closures and it will be possible to define variables in nodes there should be some functionality to check the values of variables in a scope of given node (like now we plan to have the checker of value of variables in global scope)

**Comment by awatson1978** [comment]
It would be great if the D3 rendering logic and math could be extracted out into an NPM library.  Just got assigned a decision tree as a class homework assignment, and was directed to this utility.  I'm thinking of porting it over to Meteor/React/Material-UI; since we have Electron integration already and a complete JSON data infrastructure using Mongo.

**Comment by bkamins** [comment]
@awatson1978 As you can probably see from our code base currently rendering logic is closely coupled with the rest of the GUI. We think that it is a nice approach to make such a separation into NPM library so we keep it as a future idea, as we currently have to resolve long pending requests for other functionalities.

**Comment by bkamins** [comment]
Closing this - with #95 we are finalizing feature list for 1.0.
