### ISSUE TITLE
Allow # parameter for specifying probability

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#64]
Before #38 it would be good to have `#` as parameter for specifying probabilities. Usage is to make sure in a simple way that probabilities in a chance node add up to 1.

How it should work. Assume that we have chance node `C` and its child nodes `N1`, `N2`, `Nk`.
We allow that on some (including all and none) edges `C-Ni` instead of a proper number we have `#` as a single character.

Now assume that we have *m* edges with `#` and sum of probabilities in all other edges (having proper numbers) is *p*.

If *p*>1 there should be an error `!!` by the chance node.

If *p*<=1 then in calculations each occurrence of `#` should be replaced by (1-*p*)/*m*.

By default when edges coming out of a chance node are created their probability should be filled with `#` (this is much better compared to what we have now).

A result of calculation of `#` should be shown somewhere so that user knows how much `#` is in this chance node.

**Caution!** When tree flipping #42 is used `#` should be replaced in calculation by a computed value. After tree flip we have only proper values in a tree.

**Comment by bkamins** [comment]
OK (so I treat this enhancement as prepared and remove the label), except for small things

1) after tree flip values are presented like `0.(1304347826086956521739)`, which should not be allowed (the expected functionality is to allow proper numbers (without parentheses)) as
    - no error is shown after tree flip
    - if you edit this value (enter the value in left panel but change nothing) then error shows up - the value with the parenthesis shows up an `!!` is given
2) in general following this tract I have found that we now allow to enter something like `((0.((23))))` as payoff or probability and it is allowed; this should not be allowed (it is parsed incorrectly) - only properly formatted numbers or `#` should be allowed for now (we will allow parenthesis in the future when #38 is implemented but then it should work correctly - and not it does not work properly)
3) minor issue when I have written *A result of calculation of # should be shown somewhere so that user knows how much # is in this chance node.* I meant that we should show something like `# (0.5)`, not bare `0.5` or bare `#`, as now
    - if you add *chance node* and add a *chance node* as its child `#` is printed
    - if you add *chance node* and add a *terminal node* as its child `1.0` is printed (although in left panel correctly `#` is shown)

**Comment by mwasiluk** [comment]
Any valid math.js expression in probability/payoff input is allowed now. 
The problem is that math.js expression engine doesn't parse recurring decimal numbers correctly.
To avoid recurring decimals after flipping I've changed computed probabilities format to fractions.

**Comment by mwasiluk** [comment]
E.g.   0.(13)  is parsed as 0 * 13

**Comment by bkamins** [comment]
### To do:
`Payoff`/`Probability`/`Aggregated Payoff`/`Probability to enter` should have translations (eg. under Polish SilverDecisions) and I would recommend to use sans-serif font for them

### To discuss (also @michaljakubczyk):
when performing a tree flip we always get a fraction e.g. `333/1000` in probability specification. This is OK in general (especially when we expect #38 in the future) but in simple cases a user gets `1/2` instead of `0.5`. Do you have problem with this.
A solution would be to convert fraction to decimal number if it can be done exactly (i.e. when denominator is of the form `2^p5^q`, `p,q>=0`) but do we need this?

### Documentation
@bkamins document how interpretation of formulas works (@mwasiluk could you provide me with a direct link to proper place in `maths.js` documentation so that I do not have to search for it)
@annawier document `#` functionality

**Comment by mwasiluk** [comment]
http://mathjs.org/docs/expressions/syntax.html

**Comment by mwasiluk** [comment]
Functions supported by fractions:
http://mathjs.org/docs/datatypes/fractions.html#support

**Comment by bkamins** [comment]
I decided to simply write when it is out that probabilities and payoffs support arithmetic expressions and fractions (and not mention everything else untill #38)

**Comment by bkamins** [comment]
Nice. Documentation left.

**Comment by annawier** [comment]
Documented in:
https://github.com/bkamins/SilverDecisions/wiki/3.-Actions-supported-by-application#-probability-parameter
https://github.com/bkamins/SilverDecisions/wiki/5.-Usage-tricks-and-known-issues#other-tips--tricks

PS. `#` sign is never shown on the diagram, to see it one needs to place the mouse cursor on a given probability.
