### ISSUE TITLE
Problem with mouse event handling in dev 0.4 version

### ISSUE THREAD

**Issue by pszufe** [bkamins/SilverDecisions#69]
If you select a node in a tree and want to change node selection sometimes it takes 2 mouse clicks to select a node instead of one.
It works properly in the production version. Only dev is affected

**Comment by bkamins** [comment]
@pszufe Can you give a more detailed instruction as I am unable to reproduce this behavior.

**Comment by mwasiluk** [comment]
I think that only Firefox is affected.

**Comment by bkamins** [comment]
😄 I have checked Chrome, IE and Edge.

**Comment by bkamins** [comment]
@pszufe does it work properly now. If yes please close the issue.

**Comment by pszufe** [comment]
now it's fine on FF.
