### ISSUE TITLE
Problems with JavaScript on IE

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#71]
@mwasiluk When we test with @pszufe SilverDecisions on IE it asks us for "allowed blocked content" and randomly hangs (+ some other occasional strange behaviors). Is there any general recommendation we could give in Documentation that IE users should follow to minimize the problems (other than "switch to other browser" 😄).

**Comment by mwasiluk** [comment]
I don't really know any good recommendations for IE users other than "switch to other browser" ;-)

**Comment by bkamins** [comment]
OK. I will write some more friendly comment :).
