### ISSUE TITLE
Translation files

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#72]
@pszufe Please decide with pilots which translations are needed and prepare them with @annawier.
I see the following possible translations: Italian *it*, French *fr*, Dutch *nl*, Irish *ga*, German *de*.

@mczupr please prepare German translation (@pszufe or @bkamins will tell you how).

I set it to milestone 0.6 as I would like to have it finished by then but we will deploy them as hot-fixes.
I understand that you do not need @mwasiluk for this (except for building of updated translations).

**Comment by bkamins** [comment]
I am adding hotfix milestone for issues that should be merged to master once they are done.

**Comment by bkamins** [comment]
@annawier @mczupr what are the planned dates of preparation of the translations?

**Comment by mczupr** [comment]
depends on your decision. I would prefer to work on report until end of
January and do the translation in February.

2016-12-30 10:08 GMT+01:00 Bogumił Kamiński <notifications@github.com>:

**Comment by bkamins** [comment]
@mczupr February is OK

**Comment by bkamins** [comment]
@annawier @mczupr 
Part of translation files are also in the directory `src/templates/about` (not only in `src/i18n`).
