### ISSUE TITLE
Add detection of Win7/IE11 on website

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#73]
@pszufe Following discussion with @mwasiluk please decide how to best handle the detection of Win7/IE11 on SilverDecisions website. Please do not implement it on dev so that we can merge it to main as hotfix when it is ready.

**Comment by pszufe** [comment]
@mwasiluk can we simply handle it within silverdecisions.js or we need a separate script?

**Comment by bkamins** [comment]
@pszufe Is this solved?

**Comment by pszufe** [comment]
Solved and tested - a warning message is being displayed while loading IE11 on Win 7
