### ISSUE TITLE
Update create first tree documentation

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#74]
@annawier On page:
https://github.com/bkamins/SilverDecisions/wiki/2.-Create-your-first-decision-tree-with-SilverDecisions

we should add two things:
* `#` sign (as it is automatically added to edges coming out of chance node when the treee is created)
* information that the tree shows *computed* values in payoffs and probabilities and you can see the expressions when you move mouse over the value
* information that we accept arithmetic expressions when specifying probabilities and payoffs, eg. `1+2*3`

as they might be non-intuitive for a new user of the software.

Also please review if other places of the manual should not be updated following these changes (we might have examples whose instructions need to be updated after these changes). Eg. creation of the new tree or how to get the *mouse over* effect on tablet to show the expression not the value (you have to tap), etc..

**Comment by annawier** [comment]
All of them documented in https://github.com/bkamins/
SilverDecisions/wiki/5.-Usage-tricks-and-known-issues ,
https://github.com/bkamins/SilverDecisions/wiki/4.-Application-settings
  and
https://github.com/bkamins/SilverDecisions/wiki/3.-Actions-supported-by-application

I'll check the whole documentation once again to see if it's in line with
new functionalities

2016-12-27 9:08 GMT+01:00 Bogumił Kamiński <notifications@github.com>:
