### ISSUE TITLE
Readonly seems not to work

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#75]
@mwasiluk How should read-only mode be enabled? (spotted by @annawier)

The current documentation:
https://github.com/bkamins/SilverDecisions/wiki/3.-Actions-supported-by-application#linking-to-your-decision-tree
does not work properly (and this is how I understood readonly parameter).

**Comment by mwasiluk** [comment]
It was a bug.

**Comment by bkamins** [comment]
ok. deployed
