### ISSUE TITLE
Extend set of optimization rules

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#77]
Following our discussion the following optimization rules should be implemented for now in SilverDecisions:
* `max` (should be default, previously called `classic`): maximization of expected value
* `min`: minimization of expected value
* `maxi-min`: as current (maximize in decision node, minimize in chance node)
* `maxi-max`: as current (maximize in decision node, maximize in chance node)
* `mini-min`: minimize in decision node, minimize in chance node
* `mini-max`: minimize in decision node, maximize in chance node

rules should appear in the drop down list in the order given above.

For backward compatibility when reading files from disk `classic` rule should be converted to `max` rule at file reading time (i.e. e.g. when writing back the file to disk it should be changed to `max` and in the menu `max` should be shown).

@mwasiluk I assume that this is a minor change so I mark it as hotfix (in the future more complex rules will be introduced, but they would imply new logic so I leave them out from this hotfix).
@bkamins will update the documentation after it is implemented.

**Comment by bkamins** [comment]
@mwasiluk Commit a8c6732da5 cleans up payoff calculation (also changes old calculation as it was inconsistent between maxi-min and maxi-max) I have also added a test file for all the rules in test/trees.
I will test it when a new build is made.

Currently all [maxi|mini]-[max|min] at terminal node print out probability 1/[number terminal nodes possible to reach under the decision chosen by the rule]. I have chosen this option as it quickly shows if there are other terminal nodes reachable.

Previously we had this for maxi-min and had fixed 1.0 for maxi-max.

**Comment by mwasiluk** [comment]
I've updated dist in 758abea

**Comment by bkamins** [comment]
done
