### ISSUE TITLE
Limits of values processed by SilverDecisions

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#80]
In `src/objective` calculation routines we have set fixed values that are supposed to be minimum/maximum. E.g. in `expected-value-maximization-rule.js` it is `-99999999999` for choosing the decision decision node as a bottom (and this will lead to errors if user uses smaller values).

@mwasiluk We should inform users what are the minimum and maximum values handled by SilverDecisions and @bkamins will document it. If those values are lower than `-99999999999` then we have a bug in a code (and this issue is actually a bug). Maybe this is also related to #78 and #79 (but I am not sure - there might be several things causing that behavior in conjunction).
There also might be an issue where we have an exact representation and where we have a floating point representation and rounding kicks-in. In general - we have to have this clear before #38 (when those calculations might be done under the hood and such errors would be harder to track) because this is a crucial underlying infrastructure.
We should also have it cleared before implementing #77.

**Comment by bkamins** [comment]
@mwasiluk in addition the question is why we do not use `Infinity` and `-Infinity` in the code for optimal path selection. They are parsed by `MathJS` and should always compare properly (but maybe there is some reason for the current implementation).

**Comment by mwasiluk** [comment]
Infinity should be used in the code for optimal path selection.

As to limitations.
Now we use only Fraction, so limitations are described [here](https://github.com/infusion/Fraction.js#precision):

> The biggest number representable is |Number.MAX_SAFE_INTEGER / 1| and the smallest is |1 / Number.MAX_SAFE_INTEGER|, with Number.MAX_SAFE_INTEGER=9007199254740991

In the next (0.6) version we will be using mixed number representation:
* number for expressions, which is required to support all math.js functions
* Fraction for payoffs and probabilities, with input parsed first as fraction to preserve precision (eg. 1/33), and if direct conversion fails then input will be first evaluated as expression and finally converted to Fraction.

So limitation will stay at Number.MAX_SAFE_INTEGER=9007199254740991

**Comment by bkamins** [comment]
OK. I put into the documentation that users should not use values greater than
`1 000 000 000 000 000` to be on the safe side (then even if the tree has depth 9 the aggregate will be OK).
It should be OK then.
