### ISSUE TITLE
Metadata: variable definition

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#81]
The following scenarios could work better:
1) enter `a=3` in code
2) press `Open dialog`

currently: dialog is empty
should be: dialog should contain `a=3`

1) enter `a=3` in code
2) press `Recalculate`
3) enter `a=4` in code
4) press `Open dialog`

currently: dialog is contains `a=4` but evaluation is `a=3`
should be: when `Open dialog` triggers `Recalculate` (at least this is what I would expect)

**Comment by bkamins** [comment]
@mwasiluk the second problem is fixed by today's commits, but the first one (bare `a=3` and no evaluation when no code is shown in dialog when it is opened) is not fixed.
I recommend to trigger `Recalculate` when `Open dialog` button is pressed as I guess it should solve the problem.

**Comment by bkamins** [comment]
Small issue left:
* Sometimes `Open dialog` opens dialog and sometimes performs `Recalculate` only (and does not open a dialog). The second behavior is for example in the case:
1) open new empty model
2) enter variable in `Code`
3) press `Open dialog` (and dialog does not open)

**Comment by bkamins** [comment]
@mwasiluk problem was fixed somewhere in the meantime. Do you remember which commit - for the reference?

**Comment by mwasiluk** [comment]
In 758abead617117b31bd6b6d049f8823a4446b35f by increased recomputation debounce.
