### ISSUE TITLE
Metadata: automatic recalculation

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#83]
`Recalculate` should trigger automatically when `Code` section loses focus.

In general this is the process how recalculation should work (@mwasiluk please confirm that it does this way):
* when `Recalculate` is pressed global variables and whole tree is recalculated in any *topological sorting* of nodes; each node is recalculated only once (important when `random` is used)
* `Recalculate` is automatically triggered when `Code` loses focus
* `Recalculate` is automatically triggered when `Variable definitions` dialog is closed

At least this is my opinion how it should work

**Comment by bkamins** [comment]
Additional comment regarding evaluation.
@mwasiluk Please confirm that this is an actual and intended behavior.
I set `a=10` in global scope, and then define `a=2*a` in node.
Then in this node `a=20` as it is redefined because RHS is taken from outer scope

**Comment by bkamins** [comment]
@mwasiluk another thing to decide and put into documentation:
editing of a tree does not trigger recalculation of variables. pressing `Recalculate` (only editing of `Code` sections after the fix I recommend) does. this makes a difference when formulas in payoffs/probabilities have side effects that modify variables.
alternatively we could decide that recalculation of variables is triggered every time anything is changed in a tree. I do not have a strong preference but let's decide one way or another and document it.

**Comment by mwasiluk** [comment]
> Recalculate is automatically triggered when Variable definitions dialog is closed

Is this necessary? Maybe single recomputation when the code block loses focus after its value was changed would be enough?

**Comment by bkamins** [comment]
@mwasiluk OK
@bkamins Document that change of the tree does not lead to recomputation of variables.

When it makes a difference (either way is acceptable but we need to be clear about it in documentation):

Situation 1. Consider the following global variable `a=random()`; the issue is when `a` is recomputed - either every time a tree is modified or only when `Recalculate` is pressed (we have decided for the second option)

Situation 2. consider:
```
a=[1,2]
f() = a[1] = a[1]+1
```
in global scope and a single call `f()` in one payoff.
The issue is when `a` is recomputed - either every time a tree is modified (thus `a[1]` will always be 2 in payoff) or only when `Recalculate` is pressed (thus `a[1]` will grow with every change of the tree). We have decided for the second option. It is OK as code like `f() = a[1] = a[1]+1` should be explicitly discouraged in the documentation.

**Comment by bkamins** [comment]
@mwasiluk Ah - you have asked for different thing. Yes - Recalculate has to be  triggered when Variable definitions dialog is closed.
Why? Because you can open "Variable definition dialog" without having focus in "Code" field. So recalculation only when "Code" loses focus is not enough. Is it clear what I mean?

Of course we still have manual recalculation.

**Comment by bkamins** [comment]
Just tested - works correctly and as I have described (@mwasiluk nevertheless please read my comments so that we are clear about the consequences - this "infinite incrementation" I have predicted actually happens).
