### ISSUE TITLE
Add save time to save file data

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#86]
I recommend to add `savetime` parameter to JSON format specification. It should be probably at top level just after `SilveDecisions` parameter and contain date and time of last save of the file (in the future it might be useful for automated testing using git bisect as it is more granular than version number).

**Comment by bkamins** [comment]
@mwasiluk what do `T` and `Z` mean in saved date-time:
```
  "savetime": "2017-01-25T08:00:41.430Z",
```
can they change to other symbols/strings or always `T` and `Z` will be present?

**Comment by mwasiluk** [comment]
It's [ISO 8601 UTC time format](https://en.wikipedia.org/wiki/ISO_8601)

From wiki:

> T is the time designator that precedes the time components of the representation.

> If the time is in UTC, add a Z directly after the time without a space. Z is the zone designator for the zero UTC offset
