### ISSUE TITLE
Add automated regression testing

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#87]
For JSON files in `test/trees` an automated process during build for production should check the status of their loading by SilverDecisions:
* files with suffix `_pass.json` should load without error;
* files with suffix `_fail.json` should load with error.

This is not urgent and not related to any functionality milestone so I label it hotfix.

**Comment by mwasiluk** [comment]
Maybe there should be some distinction in failure examples between 'hard' errors on file load and tree computation/validation errors?

**Comment by mwasiluk** [comment]
Maybe some suffix like `_fail_hard.json` ?

**Comment by bkamins** [comment]
OK:
* `_fail_hard.json` should mean that the format is not proper, e.g. missing fields or malformed JSON (i.e. the file is a file that was not created in SilverDecisions via save);
* `_fail.json` should mean that the tree format is OK, but data/structure is invalid (i.e. the file is a file that could be created in SilverDecisions via save);

I am adding one example of `fail_hard.json`.

**Comment by mwasiluk** [comment]
OK, I've added one fail_hard example without SilverDecisions field

**Comment by bkamins** [comment]
@mwasiluk Especially check *badx_fail_hard.json* file I have just pushed to master to decide how hard we want track down such class of malformed input.

**Comment by bkamins** [comment]
I understand that 06eafce is for your developer tests use only?

**Comment by bkamins** [comment]
@mwasiluk can we close this?

**Comment by bkamins** [comment]
I mean - additional tests will be added by me all the time, but is testing infrastructure finished on your side?

**Comment by mwasiluk** [comment]
I think it's ready
