### ISSUE TITLE
New diagram does not clear global variables

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#88]
@michaljakubczyk @mwasiluk Clicking `New diagram` leaves global variables untouched. Do we leave it or `New diagram` should clear global variables?

I see merits of both options but tend to think that global variables should be cleared.

PS. Load JSON clears global variables correctly.

**Comment by mwasiluk** [comment]
IMO global variables and code should be cleared

**Comment by michaljakubczyk** [comment]
clear’em all, in my view :)

**Comment by bkamins** [comment]
@mwasiluk so clear it is :)

**Comment by bkamins** [comment]
OK
