### ISSUE TITLE
Console logging policy

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#90]
Logging application state in console is a good policy.
What I would recommend is to set at least logging priorities: `warning` and `debug` (@mwasiluk may be more if you find it useful).

`warning` should indicate any error or warning caught when application is run. It should always be logged to the console.

`debug` should indicate any information that might be useful to developer when debugging application.

Normally, on production, only `warning` type of logging should be performed. There should be a parameter in URL like `debug=true` or something like this which will enable logging of all debug info.

@bkamins document when fix is ready: 1) logging levels, 2) what is logged as `warning` (no need to document what `debug` is logging), 3) how to enable debug mode

This is not an urgent issue so it can be implemented any time as hotfix.

**Comment by bkamins** [comment]
One thing - probably obvious; we do not need internationalization of console messages.

**Comment by mwasiluk** [comment]
We could use something like [this](https://github.com/pimterry/loglevel) to control logging.
It's about 2,3 KB minimized
It has standard logging levels implemented, so it should be easy to replace in the future with another lib if needed.

**Comment by bkamins** [comment]
this is exactly the type of tool I thought of.

**Comment by bkamins** [comment]
OK. I understand that `demo/dev` has `debug` level and `docs` has normal logging level.
