### ISSUE TITLE
Improve loading of SilverDecisions files

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#92]
When a file is loaded under SilverDecisions the following actions should be performed:

| step | test | action on error |
|-|-|-|
| 1 | is file recognized as SilverDecisions save | show dialog box with error and stop loading|
| 2 | error during loading of the file | show dialog box with error and stop loading |
| 3 | version in file newer than version of application | show dialog box with warning that some features may be missing and show tree |

By error I do not understand error in parsing of expressions or improper tree structure (this is allowed as someone might want to save an unfinished tree).

@mwasiluk two more things:
1) probably when implementing it it is worth to think about additional checks of loaded content.
2) consider adding `build_id` parameter that would additionally identify version of SilverDecisions. Usually it would be an integer indicating number of the build incremented by 1 with every build; this build number should be:
    - shown in *About* dialog in the first line as `SilverDecisions [version number] (build [build number])`
    - retained in savefile in `build_id` value that would come after `SilverDecisions` value

**Comment by mwasiluk** [comment]
maybe it would be better to store build_timestamp (unix timestamp)  instead of incremented integer?

**Comment by bkamins** [comment]
build_timestamp is OK

**Comment by mwasiluk** [comment]
Build timestamp is saved as buildTimestamp to preserve naming convention in json file

**Comment by bkamins** [comment]
@mwasiluk Can we close it? I have tested all requested features and they work, but maybe you want to add some more tests before closing.

**Comment by mwasiluk** [comment]
I think we can close it for now.
